---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/master/docker/data/logstash/config/logstash-full.yml
#
http.host: "0.0.0.0"
config.support_escapes: true
path.config: "/usr/share/logstash/pipeline"
pipeline.batch.size: 200
